name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Set up Dependencies
      run: npm i
    - name: Run Test
      run: npm test
    - name: Run Build
      run: npm run build
    - name: Run Project
      run: npm run dev
